-- Familles fournies par le client (listé FAMILLE).
-- Chaque famille est rattachée à une catégorie : MATIERE_PREMIERE (intrants/ingrédients)
-- ou EMBALLAGE (conditionnement).
INSERT INTO "families" ("code", "label", "category_id", "is_active")
SELECT v.code, v.label, c.id, true
FROM (VALUES
  ('ACIDE', 'ACIDE', 'MATIERE_PREMIERE'),
  ('ACIDIFIANT', 'ACIDIFIANT', 'MATIERE_PREMIERE'),
  ('AGENT_CROUSTILLANT', 'AGENT CROUSTILLANT', 'MATIERE_PREMIERE'),
  ('AGENT_LEVEE_BIOLO', 'AGENT DE LEVEE BIOLOGIQUE', 'MATIERE_PREMIERE'),
  ('AGENT_SERTISSAGE', 'AGENT DE SERTISSAGE EMBALLAG', 'EMBALLAGE'),
  ('AGENT_ENROBAGE', 'AGENT D''ENROBAGE', 'MATIERE_PREMIERE'),
  ('ALUMINIUM', 'ALUMINIUM', 'EMBALLAGE'),
  ('AMIDON', 'AMIDON', 'MATIERE_PREMIERE'),
  ('ANTI_BACTERIEN', 'ANTI BACTERIEN', 'MATIERE_PREMIERE'),
  ('ANTI_OXYDANT', 'ANTI OXYDANT', 'MATIERE_PREMIERE'),
  ('AROME', 'ARÔME', 'MATIERE_PREMIERE'),
  ('BASE', 'BÅSE', 'MATIERE_PREMIERE'),
  ('BASE_FOISONNANTE', 'BASE FOISONNANTE', 'MATIERE_PREMIERE'),
  ('CHAPELURE', 'CHAPELURE', 'MATIERE_PREMIERE'),
  ('COLORANT', 'COLORANT', 'MATIERE_PREMIERE'),
  ('CONSERVATEUR', 'CONSERVATEUR', 'MATIERE_PREMIERE'),
  ('DIVERS', 'DIVERS', 'MATIERE_PREMIERE'),
  ('EMBALLAGE', 'EMBALLAGE', 'EMBALLAGE'),
  ('EMULSIFIANT', 'EMULSIFIANT', 'MATIERE_PREMIERE'),
  ('ENZYME', 'ENZYME', 'MATIERE_PREMIERE'),
  ('EPAISSISSANT', 'EPAISSISSANT', 'MATIERE_PREMIERE'),
  ('FARINE', 'FARINE', 'MATIERE_PREMIERE'),
  ('FERMENT', 'FERMENT', 'MATIERE_PREMIERE'),
  ('FERMENT_LACTIQUE', 'FERMENT LACTIQUE', 'MATIERE_PREMIERE'),
  ('FILM', 'FILM', 'EMBALLAGE'),
  ('GELIFIANT', 'GELIFIANT', 'MATIERE_PREMIERE'),
  ('GRAISSE_VEGETALE', 'GRAISSE VEGETALE', 'MATIERE_PREMIERE'),
  ('HUMIDIFIANT', 'HUMIDIFIANT', 'MATIERE_PREMIERE'),
  ('LAIT', 'LAIT', 'MATIERE_PREMIERE'),
  ('LEVURE', 'LEVURE', 'MATIERE_PREMIERE'),
  ('PARAFFINE', 'PARAFFINE', 'EMBALLAGE'),
  ('PLASTIQUE', 'PLASTIQUE', 'EMBALLAGE'),
  ('PROTEINE', 'PROTEINE', 'MATIERE_PREMIERE'),
  ('RUBAN_ADHESIF', 'RUBAN ADHESIF', 'EMBALLAGE'),
  ('SEL_DE_FONTE', 'SEL DE FONTE', 'MATIERE_PREMIERE'),
  ('SOUDE', 'SOUDE', 'MATIERE_PREMIERE'),
  ('STABILISANT', 'STABILISANT', 'MATIERE_PREMIERE'),
  ('SUCRE', 'SUCRE', 'MATIERE_PREMIERE'),
  ('TEXTURANT', 'TEXTURANT', 'MATIERE_PREMIERE'),
  ('ACCESSOIRE', 'ACCESSOIRE', 'EMBALLAGE')
) AS v(code, label, cat)
LEFT JOIN "Category" c ON c.code = v.cat
ON CONFLICT ("code") DO NOTHING;